/* Generated by :claw at 2021-06-13T14:09:28.035259Z */

#if defined(__cplusplus)
#include <new>
#endif



#include "bodge_chipmunk.h"

#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#if defined(__cplusplus)
extern "C" {
#endif


__CLAW_API cpTransform* __claw_cpTransformAxialScale(cpTransform* __claw_result_, cpVect* axis, cpVect* pivot, cpFloat scale) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:187:1
(*__claw_result_) = cpTransformAxialScale(*axis, *pivot, scale);
return __claw_result_;
}

__CLAW_API void __claw_cpPinJointSetAnchorB(cpConstraint* constraint, cpVect* anchorB) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPinJoint.h:43:16
cpPinJointSetAnchorB(constraint, *anchorB);
}

__CLAW_API cpFloat __claw_cpfabs(cpFloat f) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/chipmunk_types.h:131:23
return cpfabs(f);
}

__CLAW_API cpVect* __claw_cpDampedSpringGetAnchorA(cpVect* __claw_result_, const cpConstraint* constraint) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpDampedSpring.h:39:18
(*__claw_result_) = cpDampedSpringGetAnchorA(constraint);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpDampedSpringGetAnchorB(cpVect* __claw_result_, const cpConstraint* constraint) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpDampedSpring.h:44:18
(*__claw_result_) = cpDampedSpringGetAnchorB(constraint);
return __claw_result_;
}

__CLAW_API cpFloat __claw_cpvdot(cpVect* const v1, cpVect* const v2) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:72:23
return cpvdot(*v1, *v2);
}

__CLAW_API cpVect* __claw_cpBBCenter(cpVect* __claw_result_, cpBB* bb) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:97:1
(*__claw_result_) = cpBBCenter(*bb);
return __claw_result_;
}

__CLAW_API cpFloat __claw_cpMomentForCircle(cpFloat m, cpFloat r1, cpFloat r2, cpVect* offset) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/chipmunk.h:138:19
return cpMomentForCircle(m, r1, r2, *offset);
}

__CLAW_API void __claw_cpGrooveJointSetAnchorB(cpConstraint* constraint, cpVect* anchorB) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpGrooveJoint.h:48:16
cpGrooveJointSetAnchorB(constraint, *anchorB);
}

__CLAW_API cpShape* __claw_cpSpaceSegmentQueryFirst(cpSpace* space, cpVect* start, cpVect* end, cpFloat radius, cpShapeFilter* filter, cpSegmentQueryInfo* out) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpace.h:207:20
return cpSpaceSegmentQueryFirst(space, *start, *end, radius, *filter, out);
}

__CLAW_API void __claw_cpSpatialIndexEach(cpSpatialIndex* index, cpSpatialIndexIteratorFunc func, void* data) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpatialIndex.h:169:20
cpSpatialIndexEach(index, func, data);
}

__CLAW_API cpPolyShape* __claw_cpBoxShapeInit2(cpPolyShape* poly, cpBody* body, cpBB* box, cpFloat radius) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPolyShape.h:43:24
return cpBoxShapeInit2(poly, body, *box, radius);
}

__CLAW_API cpVect* __claw_cpvrperp(cpVect* __claw_result_, cpVect* const v) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:92:22
(*__claw_result_) = cpvrperp(*v);
return __claw_result_;
}

__CLAW_API cpTransform* __claw_cpTransformRotate(cpTransform* __claw_result_, cpFloat radians) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:122:1
(*__claw_result_) = cpTransformRotate(radians);
return __claw_result_;
}

__CLAW_API cpFloat __claw_cpMomentForSegment(cpFloat m, cpVect* a, cpVect* b, cpFloat radius) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/chipmunk.h:146:19
return cpMomentForSegment(m, *a, *b, radius);
}

__CLAW_API void __claw_cpSpatialIndexReindex(cpSpatialIndex* index) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpatialIndex.h:196:20
cpSpatialIndexReindex(index);
}

__CLAW_API cpBool __claw_cpShapeSegmentQuery(const cpShape* shape, cpVect* a, cpVect* b, cpFloat radius, cpSegmentQueryInfo* info) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:92:18
return cpShapeSegmentQuery(shape, *a, *b, radius, info);
}

__CLAW_API cpBB* __claw_cpBBNew(cpBB* __claw_result_, const cpFloat l, const cpFloat b, const cpFloat r, const cpFloat t) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:38:20
(*__claw_result_) = cpBBNew(l, b, r, t);
return __claw_result_;
}

__CLAW_API cpContactPointSet* __claw_cpShapesCollide(cpContactPointSet* __claw_result_, const cpShape* a, const cpShape* b) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:95:29
(*__claw_result_) = cpShapesCollide(a, b);
return __claw_result_;
}

__CLAW_API cpShapeFilter* __claw_cpShapeFilterNew(cpShapeFilter* __claw_result_, cpGroup group, cpBitmask categories, cpBitmask mask) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:71:1
(*__claw_result_) = cpShapeFilterNew(group, categories, mask);
return __claw_result_;
}

__CLAW_API cpShape* __claw_cpPolyShapeNew(cpBody* body, int count, const cpVect* verts, cpTransform* transform, cpFloat radius) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPolyShape.h:35:20
return cpPolyShapeNew(body, count, verts, *transform, radius);
}

__CLAW_API cpVect* __claw_cpBodyGetForce(cpVect* __claw_result_, const cpBody* body) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:113:18
(*__claw_result_) = cpBodyGetForce(body);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpBodyWorldToLocal(cpVect* __claw_result_, const cpBody* body, cpVect* const point) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:154:18
(*__claw_result_) = cpBodyWorldToLocal(body, *point);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpArbiterGetPointB(cpVect* __claw_result_, const cpArbiter* arb, int i) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpArbiter.h:117:18
(*__claw_result_) = cpArbiterGetPointB(arb, i);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpArbiterGetPointA(cpVect* __claw_result_, const cpArbiter* arb, int i) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpArbiter.h:115:18
(*__claw_result_) = cpArbiterGetPointA(arb, i);
return __claw_result_;
}

__CLAW_API cpSlideJoint* __claw_cpSlideJointInit(cpSlideJoint* joint, cpBody* a, cpBody* b, cpVect* anchorA, cpVect* anchorB, cpFloat min, cpFloat max) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSlideJoint.h:31:25
return cpSlideJointInit(joint, a, b, *anchorA, *anchorB, min, max);
}

__CLAW_API void __claw_cpShapeSetFilter(cpShape* shape, cpShapeFilter* filter) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:159:16
cpShapeSetFilter(shape, *filter);
}

__CLAW_API void __claw_cpBodyUpdateVelocity(cpBody* body, cpVect* gravity, cpFloat damping, cpFloat dt) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:147:16
cpBodyUpdateVelocity(body, *gravity, damping, dt);
}

__CLAW_API cpVect* __claw_cpvperp(cpVect* __claw_result_, cpVect* const v) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:86:22
(*__claw_result_) = cpvperp(*v);
return __claw_result_;
}

__CLAW_API void __claw_cpGrooveJointSetGrooveB(cpConstraint* constraint, cpVect* grooveB) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpGrooveJoint.h:43:16
cpGrooveJointSetGrooveB(constraint, *grooveB);
}

__CLAW_API cpBB* __claw_cpShapeGetBB(cpBB* __claw_result_, const cpShape* shape) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:124:16
(*__claw_result_) = cpShapeGetBB(shape);
return __claw_result_;
}

__CLAW_API void __claw_cpArbiterSetSurfaceVelocity(cpArbiter* arb, cpVect* vr) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpArbiter.h:45:16
cpArbiterSetSurfaceVelocity(arb, *vr);
}

__CLAW_API void __claw_cpGrooveJointSetGrooveA(cpConstraint* constraint, cpVect* grooveA) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpGrooveJoint.h:38:16
cpGrooveJointSetGrooveA(constraint, *grooveA);
}

__CLAW_API cpVect* __claw_cpBodyLocalToWorld(cpVect* __claw_result_, const cpBody* body, cpVect* const point) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:152:18
(*__claw_result_) = cpBodyLocalToWorld(body, *point);
return __claw_result_;
}

__CLAW_API cpFloat __claw_cpAreaForSegment(cpVect* a, cpVect* b, cpFloat radius) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/chipmunk.h:149:19
return cpAreaForSegment(*a, *b, radius);
}

__CLAW_API cpVect* __claw_cpBodyGetPosition(cpVect* __claw_result_, const cpBody* body) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:98:18
(*__claw_result_) = cpBodyGetPosition(body);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpvunrotate(cpVect* __claw_result_, cpVect* const v1, cpVect* const v2) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:122:22
(*__claw_result_) = cpvunrotate(*v1, *v2);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpTransformVect(cpVect* __claw_result_, cpTransform* t, cpVect* v) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:81:1
(*__claw_result_) = cpTransformVect(*t, *v);
return __claw_result_;
}

__CLAW_API cpConstraint* __claw_cpDampedSpringNew(cpBody* a, cpBody* b, cpVect* anchorA, cpVect* anchorB, cpFloat restLength, cpFloat stiffness, cpFloat damping) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpDampedSpring.h:36:25
return cpDampedSpringNew(a, b, *anchorA, *anchorB, restLength, stiffness, damping);
}

__CLAW_API cpVect* __claw_cpSpaceGetGravity(cpVect* __claw_result_, const cpSpace* space) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpace.h:87:18
(*__claw_result_) = cpSpaceGetGravity(space);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpClosetPointOnSegment(cpVect* __claw_result_, cpVect* const p, cpVect* const a, cpVect* const b) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/chipmunk.h:183:1
(*__claw_result_) = cpClosetPointOnSegment(*p, *a, *b);
return __claw_result_;
}

__CLAW_API cpPinJoint* __claw_cpPinJointInit(cpPinJoint* joint, cpBody* a, cpBody* b, cpVect* anchorA, cpVect* anchorB) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPinJoint.h:31:23
return cpPinJointInit(joint, a, b, *anchorA, *anchorB);
}

__CLAW_API cpFloat __claw_cpfclamp(cpFloat f, cpFloat min, cpFloat max) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/chipmunk_types.h:137:23
return cpfclamp(f, min, max);
}

__CLAW_API cpFloat __claw_cpMomentForBox2(cpFloat m, cpBB* box) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/chipmunk.h:165:19
return cpMomentForBox2(m, *box);
}

__CLAW_API cpBool __claw_cpSpatialIndexContains(cpSpatialIndex* index, void* obj, cpHashValue hashid) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpatialIndex.h:176:22
return cpSpatialIndexContains(index, obj, hashid);
}

__CLAW_API cpTransform* __claw_cpTransformOrtho(cpTransform* __claw_result_, cpBB* bb) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:168:1
(*__claw_result_) = cpTransformOrtho(*bb);
return __claw_result_;
}

__CLAW_API cpShape* __claw_cpBoxShapeNew2(cpBody* body, cpBB* box, cpFloat radius) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPolyShape.h:47:20
return cpBoxShapeNew2(body, *box, radius);
}

__CLAW_API cpPivotJoint* __claw_cpPivotJointInit(cpPivotJoint* joint, cpBody* a, cpBody* b, cpVect* anchorA, cpVect* anchorB) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPivotJoint.h:31:25
return cpPivotJointInit(joint, a, b, *anchorA, *anchorB);
}

__CLAW_API void __claw_cpDampedSpringSetAnchorB(cpConstraint* constraint, cpVect* anchorB) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpDampedSpring.h:46:16
cpDampedSpringSetAnchorB(constraint, *anchorB);
}

__CLAW_API cpFloat __claw_cpShapePointQuery(const cpShape* shape, cpVect* p, cpPointQueryInfo* out) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:89:19
return cpShapePointQuery(shape, *p, out);
}

__CLAW_API cpVect* __claw_cpvlerpconst(cpVect* __claw_result_, cpVect* v1, cpVect* v2, cpFloat d) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:185:22
(*__claw_result_) = cpvlerpconst(*v1, *v2, d);
return __claw_result_;
}

__CLAW_API cpTransform* __claw_cpTransformNew(cpTransform* __claw_result_, cpFloat a, cpFloat b, cpFloat c, cpFloat d, cpFloat tx, cpFloat ty) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:37:1
(*__claw_result_) = cpTransformNew(a, b, c, d, tx, ty);
return __claw_result_;
}

__CLAW_API void __claw_cpSpatialIndexSegmentQuery(cpSpatialIndex* index, void* obj, cpVect* a, cpVect* b, cpFloat t_exit, cpSpatialIndexSegmentQueryFunc func, void* data) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpatialIndex.h:214:20
cpSpatialIndexSegmentQuery(index, obj, *a, *b, t_exit, func, data);
}

__CLAW_API cpFloat __claw_cpBBMergedArea(cpBB* a, cpBB* b) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:109:23
return cpBBMergedArea(*a, *b);
}

__CLAW_API cpFloat __claw_cpfclamp01(cpFloat f) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/chipmunk_types.h:143:23
return cpfclamp01(f);
}

__CLAW_API void __claw_cpSpatialIndexRemove(cpSpatialIndex* index, void* obj, cpHashValue hashid) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpatialIndex.h:190:20
cpSpatialIndexRemove(index, obj, hashid);
}

__CLAW_API cpTransform* __claw_cpTransformMult(cpTransform* __claw_result_, cpTransform* t1, cpTransform* t2) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:64:1
(*__claw_result_) = cpTransformMult(*t1, *t2);
return __claw_result_;
}

__CLAW_API cpBool __claw_cpBBContainsVect(cpBB* const bb, cpVect* const v) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:70:22
return cpBBContainsVect(*bb, *v);
}

__CLAW_API cpVect* __claw_cpPolyShapeGetVert(cpVect* __claw_result_, const cpShape* shape, int index) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPolyShape.h:52:18
(*__claw_result_) = cpPolyShapeGetVert(shape, index);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpvrotate(cpVect* __claw_result_, cpVect* const v1, cpVect* const v2) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:116:22
(*__claw_result_) = cpvrotate(*v1, *v2);
return __claw_result_;
}

__CLAW_API void __claw_cpDampedSpringSetAnchorA(cpConstraint* constraint, cpVect* anchorA) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpDampedSpring.h:41:16
cpDampedSpringSetAnchorA(constraint, *anchorA);
}

__CLAW_API void __claw_cpBodyApplyImpulseAtLocalPoint(cpBody* body, cpVect* impulse, cpVect* point) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:164:16
cpBodyApplyImpulseAtLocalPoint(body, *impulse, *point);
}

__CLAW_API cpVect* __claw_cpBBClampVect(cpVect* __claw_result_, cpBB* const bb, cpVect* const v) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:153:1
(*__claw_result_) = cpBBClampVect(*bb, *v);
return __claw_result_;
}

__CLAW_API cpBB* __claw_cpShapeCacheBB(cpBB* __claw_result_, cpShape* shape) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:83:16
(*__claw_result_) = cpShapeCacheBB(shape);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpvnormalize(cpVect* __claw_result_, cpVect* const v) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:146:22
(*__claw_result_) = cpvnormalize(*v);
return __claw_result_;
}

__CLAW_API cpMat2x2* __claw_cpMat2x2New(cpMat2x2* __claw_result_, cpFloat a, cpFloat b, cpFloat c, cpFloat d) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:216:1
(*__claw_result_) = cpMat2x2New(a, b, c, d);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpvslerp(cpVect* __claw_result_, cpVect* const v1, cpVect* const v2, const cpFloat t) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:154:1
(*__claw_result_) = cpvslerp(*v1, *v2, t);
return __claw_result_;
}

__CLAW_API cpGrooveJoint* __claw_cpGrooveJointInit(cpGrooveJoint* joint, cpBody* a, cpBody* b, cpVect* groove_a, cpVect* groove_b, cpVect* anchorB) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpGrooveJoint.h:31:26
return cpGrooveJointInit(joint, a, b, *groove_a, *groove_b, *anchorB);
}

__CLAW_API cpSegmentShape* __claw_cpSegmentShapeInit(cpSegmentShape* seg, cpBody* body, cpVect* a, cpVect* b, cpFloat radius) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:183:27
return cpSegmentShapeInit(seg, body, *a, *b, radius);
}

__CLAW_API cpVect* __claw_cpvmult(cpVect* __claw_result_, cpVect* const v, const cpFloat s) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:66:22
(*__claw_result_) = cpvmult(*v, s);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpSegmentShapeGetA(cpVect* __claw_result_, const cpShape* shape) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:191:18
(*__claw_result_) = cpSegmentShapeGetA(shape);
return __claw_result_;
}

__CLAW_API cpFloat __claw_cpvlengthsq(cpVect* const v) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:128:23
return cpvlengthsq(*v);
}

__CLAW_API cpBB* __claw_cpBBOffset(cpBB* __claw_result_, cpBB* const bb, cpVect* const v) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:175:1
(*__claw_result_) = cpBBOffset(*bb, *v);
return __claw_result_;
}

__CLAW_API cpBB* __claw_cpBBNewForExtents(cpBB* __claw_result_, cpVect* const c, const cpFloat hw, const cpFloat hh) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:46:1
(*__claw_result_) = cpBBNewForExtents(*c, hw, hh);
return __claw_result_;
}

__CLAW_API void __claw_cpBodyApplyForceAtWorldPoint(cpBody* body, cpVect* force, cpVect* point) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:157:16
cpBodyApplyForceAtWorldPoint(body, *force, *point);
}

__CLAW_API cpVect* __claw_cpBodyGetRotation(cpVect* __claw_result_, const cpBody* body) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:133:18
(*__claw_result_) = cpBodyGetRotation(body);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpvproject(cpVect* __claw_result_, cpVect* const v1, cpVect* const v2) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:98:22
(*__claw_result_) = cpvproject(*v1, *v2);
return __claw_result_;
}

__CLAW_API cpConstraint* __claw_cpGrooveJointNew(cpBody* a, cpBody* b, cpVect* groove_a, cpVect* groove_b, cpVect* anchorB) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpGrooveJoint.h:33:25
return cpGrooveJointNew(a, b, *groove_a, *groove_b, *anchorB);
}

__CLAW_API cpVect* __claw_cpv(cpVect* __claw_result_, const cpFloat x, const cpFloat y) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:35:22
(*__claw_result_) = cpv(x, y);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpCircleShapeGetOffset(cpVect* __claw_result_, const cpShape* shape) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:173:18
(*__claw_result_) = cpCircleShapeGetOffset(shape);
return __claw_result_;
}

__CLAW_API cpFloat __claw_cpflerp(cpFloat f1, cpFloat f2, cpFloat t) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/chipmunk_types.h:151:23
return cpflerp(f1, f2, t);
}

__CLAW_API cpVect* __claw_cpvforangle(cpVect* __claw_result_, const cpFloat a) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:104:22
(*__claw_result_) = cpvforangle(a);
return __claw_result_;
}

__CLAW_API cpShape* __claw_cpSpacePointQueryNearest(cpSpace* space, cpVect* point, cpFloat maxDistance, cpShapeFilter* filter, cpPointQueryInfo* out) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpace.h:200:20
return cpSpacePointQueryNearest(space, *point, maxDistance, *filter, out);
}

__CLAW_API cpTransform* __claw_cpTransformInverse(cpTransform* __claw_result_, cpTransform* t) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:53:1
(*__claw_result_) = cpTransformInverse(*t);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpvclamp(cpVect* __claw_result_, cpVect* const v, const cpFloat len) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:179:22
(*__claw_result_) = cpvclamp(*v, len);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpPinJointGetAnchorA(cpVect* __claw_result_, const cpConstraint* constraint) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPinJoint.h:36:18
(*__claw_result_) = cpPinJointGetAnchorA(constraint);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpPinJointGetAnchorB(cpVect* __claw_result_, const cpConstraint* constraint) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPinJoint.h:41:18
(*__claw_result_) = cpPinJointGetAnchorB(constraint);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpPivotJointGetAnchorB(cpVect* __claw_result_, const cpConstraint* constraint) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPivotJoint.h:43:18
(*__claw_result_) = cpPivotJointGetAnchorB(constraint);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpPivotJointGetAnchorA(cpVect* __claw_result_, const cpConstraint* constraint) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPivotJoint.h:38:18
(*__claw_result_) = cpPivotJointGetAnchorA(constraint);
return __claw_result_;
}

__CLAW_API cpTransform* __claw_cpTransformRigid(cpTransform* __claw_result_, cpVect* translate, cpFloat radians) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:133:1
(*__claw_result_) = cpTransformRigid(*translate, radians);
return __claw_result_;
}

__CLAW_API cpContactPointSet* __claw_cpArbiterGetContactPointSet(cpContactPointSet* __claw_result_, const cpArbiter* arb) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpArbiter.h:99:29
(*__claw_result_) = cpArbiterGetContactPointSet(arb);
return __claw_result_;
}

__CLAW_API cpConstraint* __claw_cpPinJointNew(cpBody* a, cpBody* b, cpVect* anchorA, cpVect* anchorB) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPinJoint.h:33:25
return cpPinJointNew(a, b, *anchorA, *anchorB);
}

__CLAW_API cpVect* __claw_cpArbiterGetSurfaceVelocity(cpVect* __claw_result_, cpArbiter* arb) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpArbiter.h:41:18
(*__claw_result_) = cpArbiterGetSurfaceVelocity(arb);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpArbiterTotalImpulse(cpVect* __claw_result_, const cpArbiter* arb) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpArbiter.h:55:18
(*__claw_result_) = cpArbiterTotalImpulse(arb);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpGrooveJointGetAnchorB(cpVect* __claw_result_, const cpConstraint* constraint) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpGrooveJoint.h:46:18
(*__claw_result_) = cpGrooveJointGetAnchorB(constraint);
return __claw_result_;
}

__CLAW_API void __claw_cpSpaceSegmentQuery(cpSpace* space, cpVect* start, cpVect* end, cpFloat radius, cpShapeFilter* filter, cpSpaceSegmentQueryFunc func, void* data) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpace.h:205:16
cpSpaceSegmentQuery(space, *start, *end, radius, *filter, func, data);
}

__CLAW_API cpVect* __claw_cpShapeGetSurfaceVelocity(cpVect* __claw_result_, const cpShape* shape) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:142:18
(*__claw_result_) = cpShapeGetSurfaceVelocity(shape);
return __claw_result_;
}

__CLAW_API cpShape* __claw_cpSegmentShapeNew(cpBody* body, cpVect* a, cpVect* b, cpFloat radius) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:185:20
return cpSegmentShapeNew(body, *a, *b, radius);
}

__CLAW_API cpVect* __claw_cpSegmentShapeGetB(cpVect* __claw_result_, const cpShape* shape) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:193:18
(*__claw_result_) = cpSegmentShapeGetB(shape);
return __claw_result_;
}

__CLAW_API cpBB* __claw_cpShapeUpdate(cpBB* __claw_result_, cpShape* shape, cpTransform* transform) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:85:16
(*__claw_result_) = cpShapeUpdate(shape, *transform);
return __claw_result_;
}

__CLAW_API void __claw_cpBodyApplyImpulseAtWorldPoint(cpBody* body, cpVect* impulse, cpVect* point) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:162:16
cpBodyApplyImpulseAtWorldPoint(body, *impulse, *point);
}

__CLAW_API int __claw_cpSpatialIndexCount(cpSpatialIndex* index) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpatialIndex.h:163:19
return cpSpatialIndexCount(index);
}

__CLAW_API cpFloat __claw_cpvdist(cpVect* const v1, cpVect* const v2) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:191:23
return cpvdist(*v1, *v2);
}

__CLAW_API cpFloat __claw_cpvcross(cpVect* const v1, cpVect* const v2) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:80:23
return cpvcross(*v1, *v2);
}

__CLAW_API cpBB* __claw_cpBBExpand(cpBB* __claw_result_, cpBB* const bb, cpVect* const v) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:86:20
(*__claw_result_) = cpBBExpand(*bb, *v);
return __claw_result_;
}

__CLAW_API cpFloat __claw_cpfmin(cpFloat a, cpFloat b) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/chipmunk_types.h:125:23
return cpfmin(a, b);
}

__CLAW_API cpFloat __claw_cpvdistsq(cpVect* const v1, cpVect* const v2) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:197:23
return cpvdistsq(*v1, *v2);
}

__CLAW_API cpVect* __claw_cpvslerpconst(cpVect* __claw_result_, cpVect* const v1, cpVect* const v2, const cpFloat a) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:170:1
(*__claw_result_) = cpvslerpconst(*v1, *v2, a);
return __claw_result_;
}

__CLAW_API cpBB* __claw_cpTransformbBB(cpBB* __claw_result_, cpTransform* t, cpBB* bb) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:88:1
(*__claw_result_) = cpTransformbBB(*t, *bb);
return __claw_result_;
}

__CLAW_API cpBool __claw_cpBBContainsBB(cpBB* const bb, cpBB* const other) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:64:22
return cpBBContainsBB(*bb, *other);
}

__CLAW_API cpBool __claw_cpvnear(cpVect* const v1, cpVect* const v2, const cpFloat dist) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:203:22
return cpvnear(*v1, *v2, dist);
}

__CLAW_API void __claw_cpSlideJointSetAnchorB(cpConstraint* constraint, cpVect* anchorB) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSlideJoint.h:43:16
cpSlideJointSetAnchorB(constraint, *anchorB);
}

__CLAW_API cpVect* __claw_cpBodyGetVelocityAtLocalPoint(cpVect* __claw_result_, const cpBody* body, cpVect* point) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:169:18
(*__claw_result_) = cpBodyGetVelocityAtLocalPoint(body, *point);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpMat2x2Transform(cpVect* __claw_result_, cpMat2x2* m, cpVect* v) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:223:1
(*__claw_result_) = cpMat2x2Transform(*m, *v);
return __claw_result_;
}

__CLAW_API void __claw_cpSlideJointSetAnchorA(cpConstraint* constraint, cpVect* anchorA) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSlideJoint.h:38:16
cpSlideJointSetAnchorA(constraint, *anchorA);
}

__CLAW_API cpVect* __claw_cpArbiterGetNormal(cpVect* __claw_result_, const cpArbiter* arb) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpArbiter.h:113:18
(*__claw_result_) = cpArbiterGetNormal(arb);
return __claw_result_;
}

__CLAW_API cpBB* __claw_cpBBMerge(cpBB* __claw_result_, cpBB* const a, cpBB* const b) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:76:20
(*__claw_result_) = cpBBMerge(*a, *b);
return __claw_result_;
}

__CLAW_API cpPolyShape* __claw_cpPolyShapeInit(cpPolyShape* poly, cpBody* body, int count, const cpVect* verts, cpTransform* transform, cpFloat radius) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPolyShape.h:29:24
return cpPolyShapeInit(poly, body, count, verts, *transform, radius);
}

__CLAW_API cpVect* __claw_cpBodyGetCenterOfGravity(cpVect* __claw_result_, const cpBody* body) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:103:18
(*__claw_result_) = cpBodyGetCenterOfGravity(body);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpGrooveJointGetGrooveB(cpVect* __claw_result_, const cpConstraint* constraint) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpGrooveJoint.h:41:18
(*__claw_result_) = cpGrooveJointGetGrooveB(constraint);
return __claw_result_;
}

__CLAW_API cpFloat __claw_cpMomentForPoly(cpFloat m, int count, const cpVect* verts, cpVect* offset, cpFloat radius) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/chipmunk.h:152:19
return cpMomentForPoly(m, count, verts, *offset, radius);
}

__CLAW_API cpVect* __claw_cpGrooveJointGetGrooveA(cpVect* __claw_result_, const cpConstraint* constraint) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpGrooveJoint.h:36:18
(*__claw_result_) = cpGrooveJointGetGrooveA(constraint);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpvadd(cpVect* __claw_result_, cpVect* const v1, cpVect* const v2) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:48:22
(*__claw_result_) = cpvadd(*v1, *v2);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpShapeGetCenterOfGravity(cpVect* __claw_result_, cpShape* shape) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:121:18
(*__claw_result_) = cpShapeGetCenterOfGravity(shape);
return __claw_result_;
}

__CLAW_API void __claw_cpSpatialIndexReindexQuery(cpSpatialIndex* index, cpSpatialIndexQueryFunc func, void* data) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpatialIndex.h:222:20
cpSpatialIndexReindexQuery(index, func, data);
}

__CLAW_API cpCircleShape* __claw_cpCircleShapeInit(cpCircleShape* circle, cpBody* body, cpFloat radius, cpVect* offset) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:168:26
return cpCircleShapeInit(circle, body, radius, *offset);
}

__CLAW_API cpConstraint* __claw_cpSlideJointNew(cpBody* a, cpBody* b, cpVect* anchorA, cpVect* anchorB, cpFloat min, cpFloat max) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSlideJoint.h:33:25
return cpSlideJointNew(a, b, *anchorA, *anchorB, min, max);
}

__CLAW_API void __claw_cpSegmentShapeSetNeighbors(cpShape* shape, cpVect* prev, cpVect* next) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:188:16
cpSegmentShapeSetNeighbors(shape, *prev, *next);
}

__CLAW_API cpVect* __claw_cpBodyGetVelocityAtWorldPoint(cpVect* __claw_result_, const cpBody* body, cpVect* point) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:167:18
(*__claw_result_) = cpBodyGetVelocityAtWorldPoint(body, *point);
return __claw_result_;
}

__CLAW_API void __claw_cpSpacePointQuery(cpSpace* space, cpVect* point, cpFloat maxDistance, cpShapeFilter* filter, cpSpacePointQueryFunc func, void* data) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpace.h:198:16
cpSpacePointQuery(space, *point, maxDistance, *filter, func, data);
}

__CLAW_API void __claw_cpBodySetVelocity(cpBody* body, cpVect* velocity) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:110:16
cpBodySetVelocity(body, *velocity);
}

__CLAW_API cpTransform* __claw_cpTransformWrapInverse(cpTransform* __claw_result_, cpTransform* outer, cpTransform* inner) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:162:1
(*__claw_result_) = cpTransformWrapInverse(*outer, *inner);
return __claw_result_;
}

__CLAW_API cpBool __claw_cpBBIntersectsSegment(cpBB* bb, cpVect* a, cpVect* b) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:146:22
return cpBBIntersectsSegment(*bb, *a, *b);
}

__CLAW_API void __claw_cpPivotJointSetAnchorB(cpConstraint* constraint, cpVect* anchorB) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPivotJoint.h:45:16
cpPivotJointSetAnchorB(constraint, *anchorB);
}

__CLAW_API void __claw_cpSpatialIndexDestroy(cpSpatialIndex* index) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpatialIndex.h:157:20
cpSpatialIndexDestroy(index);
}

__CLAW_API cpDampedSpring* __claw_cpDampedSpringInit(cpDampedSpring* joint, cpBody* a, cpBody* b, cpVect* anchorA, cpVect* anchorB, cpFloat restLength, cpFloat stiffness, cpFloat damping) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpDampedSpring.h:34:27
return cpDampedSpringInit(joint, a, b, *anchorA, *anchorB, restLength, stiffness, damping);
}

__CLAW_API cpBB* __claw_cpBBNewForCircle(cpBB* __claw_result_, cpVect* const p, const cpFloat r) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:52:20
(*__claw_result_) = cpBBNewForCircle(*p, r);
return __claw_result_;
}

__CLAW_API cpTransform* __claw_cpTransformBoneScale(cpTransform* __claw_result_, cpVect* v0, cpVect* v1) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:177:1
(*__claw_result_) = cpTransformBoneScale(*v0, *v1);
return __claw_result_;
}

__CLAW_API void __claw_cpPivotJointSetAnchorA(cpConstraint* constraint, cpVect* anchorA) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPivotJoint.h:40:16
cpPivotJointSetAnchorA(constraint, *anchorA);
}

__CLAW_API void __claw_cpSpatialIndexReindexObject(cpSpatialIndex* index, void* obj, cpHashValue hashid) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpatialIndex.h:202:20
cpSpatialIndexReindexObject(index, obj, hashid);
}

__CLAW_API cpVect* __claw_cpBodyGetVelocity(cpVect* __claw_result_, const cpBody* body) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:108:18
(*__claw_result_) = cpBodyGetVelocity(body);
return __claw_result_;
}

__CLAW_API cpFloat __claw_cpfmax(cpFloat a, cpFloat b) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/chipmunk_types.h:119:23
return cpfmax(a, b);
}

__CLAW_API void __claw_cpBodySetForce(cpBody* body, cpVect* force) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:115:16
cpBodySetForce(body, *force);
}

__CLAW_API cpConstraint* __claw_cpPivotJointNew(cpBody* a, cpBody* b, cpVect* pivot) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPivotJoint.h:33:25
return cpPivotJointNew(a, b, *pivot);
}

__CLAW_API cpVect* __claw_cpvsub(cpVect* __claw_result_, cpVect* const v1, cpVect* const v2) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:54:22
(*__claw_result_) = cpvsub(*v1, *v2);
return __claw_result_;
}

__CLAW_API void __claw_cpPinJointSetAnchorA(cpConstraint* constraint, cpVect* anchorA) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPinJoint.h:38:16
cpPinJointSetAnchorA(constraint, *anchorA);
}

__CLAW_API cpVect* __claw_cpvlerp(cpVect* __claw_result_, cpVect* const v1, cpVect* const v2, const cpFloat t) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:140:22
(*__claw_result_) = cpvlerp(*v1, *v2, t);
return __claw_result_;
}

__CLAW_API cpFloat __claw_cpflerpconst(cpFloat f1, cpFloat f2, cpFloat d) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/chipmunk_types.h:157:23
return cpflerpconst(f1, f2, d);
}

__CLAW_API cpTransform* __claw_cpTransformRigidInverse(cpTransform* __claw_result_, cpTransform* t) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:144:1
(*__claw_result_) = cpTransformRigidInverse(*t);
return __claw_result_;
}

__CLAW_API void __claw_cpShapeSetSurfaceVelocity(cpShape* shape, cpVect* surfaceVelocity) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:144:16
cpShapeSetSurfaceVelocity(shape, *surfaceVelocity);
}

__CLAW_API cpVect* __claw_cpCentroidForPoly(cpVect* __claw_result_, const int count, const cpVect* verts) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/chipmunk.h:159:18
(*__claw_result_) = cpCentroidForPoly(count, verts);
return __claw_result_;
}

__CLAW_API void __claw_cpSpatialIndexInsert(cpSpatialIndex* index, void* obj, cpHashValue hashid) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpatialIndex.h:183:20
cpSpatialIndexInsert(index, obj, hashid);
}

__CLAW_API cpBool __claw_cpBBIntersects(cpBB* const a, cpBB* const b) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:58:22
return cpBBIntersects(*a, *b);
}

__CLAW_API cpTransform* __claw_cpTransformTranslate(cpTransform* __claw_result_, cpVect* translate) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:102:1
(*__claw_result_) = cpTransformTranslate(*translate);
return __claw_result_;
}

__CLAW_API cpFloat __claw_cpvlength(cpVect* const v) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:134:23
return cpvlength(*v);
}

__CLAW_API cpFloat __claw_cpBBSegmentQuery(cpBB* bb, cpVect* a, cpVect* b) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:115:23
return cpBBSegmentQuery(*bb, *a, *b);
}

__CLAW_API void __claw_cpSpaceSetGravity(cpSpace* space, cpVect* gravity) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpace.h:88:16
cpSpaceSetGravity(space, *gravity);
}

__CLAW_API cpConstraint* __claw_cpPivotJointNew2(cpBody* a, cpBody* b, cpVect* anchorA, cpVect* anchorB) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpPivotJoint.h:35:25
return cpPivotJointNew2(a, b, *anchorA, *anchorB);
}

__CLAW_API void __claw_cpSpaceBBQuery(cpSpace* space, cpBB* bb, cpShapeFilter* filter, cpSpaceBBQueryFunc func, void* data) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpace.h:213:16
cpSpaceBBQuery(space, *bb, *filter, func, data);
}

__CLAW_API cpFloat __claw_cpvtoangle(cpVect* const v) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:110:23
return cpvtoangle(*v);
}

__CLAW_API void __claw_cpBodySetPosition(cpBody* body, cpVect* pos) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:100:16
cpBodySetPosition(body, *pos);
}

__CLAW_API cpFloat __claw_cpBBArea(cpBB* bb) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:103:23
return cpBBArea(*bb);
}

__CLAW_API void __claw_cpBodySetCenterOfGravity(cpBody* body, cpVect* cog) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:105:16
cpBodySetCenterOfGravity(body, *cog);
}

__CLAW_API cpTransform* __claw_cpTransformWrap(cpTransform* __claw_result_, cpTransform* outer, cpTransform* inner) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:156:1
(*__claw_result_) = cpTransformWrap(*outer, *inner);
return __claw_result_;
}

__CLAW_API cpTransform* __claw_cpTransformScale(cpTransform* __claw_result_, cpFloat scaleX, cpFloat scaleY) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:112:1
(*__claw_result_) = cpTransformScale(scaleX, scaleY);
return __claw_result_;
}

__CLAW_API void __claw_cpBodyApplyForceAtLocalPoint(cpBody* body, cpVect* force, cpVect* point) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBody.h:159:16
cpBodyApplyForceAtLocalPoint(body, *force, *point);
}

__CLAW_API cpVect* __claw_cpSlideJointGetAnchorB(cpVect* __claw_result_, const cpConstraint* constraint) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSlideJoint.h:41:18
(*__claw_result_) = cpSlideJointGetAnchorB(constraint);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpSegmentShapeGetNormal(cpVect* __claw_result_, const cpShape* shape) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:195:18
(*__claw_result_) = cpSegmentShapeGetNormal(shape);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpTransformPoint(cpVect* __claw_result_, cpTransform* t, cpVect* p) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:74:1
(*__claw_result_) = cpTransformPoint(*t, *p);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpSlideJointGetAnchorA(cpVect* __claw_result_, const cpConstraint* constraint) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSlideJoint.h:36:18
(*__claw_result_) = cpSlideJointGetAnchorA(constraint);
return __claw_result_;
}

__CLAW_API cpTransform* __claw_cpTransformNewTranspose(cpTransform* __claw_result_, cpFloat a, cpFloat c, cpFloat tx, cpFloat b, cpFloat d, cpFloat ty) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpTransform.h:45:1
(*__claw_result_) = cpTransformNewTranspose(a, c, tx, b, d, ty);
return __claw_result_;
}

__CLAW_API cpVect* __claw_cpBBWrapVect(cpVect* __claw_result_, cpBB* const bb, cpVect* const v) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpBB.h:160:1
(*__claw_result_) = cpBBWrapVect(*bb, *v);
return __claw_result_;
}

__CLAW_API cpBool __claw_cpveql(cpVect* const v1, cpVect* const v2) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:42:22
return cpveql(*v1, *v2);
}

__CLAW_API cpVect* __claw_cpvneg(cpVect* __claw_result_, cpVect* const v) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpVect.h:60:22
(*__claw_result_) = cpvneg(*v);
return __claw_result_;
}

__CLAW_API void __claw_cpSpatialIndexQuery(cpSpatialIndex* index, void* obj, cpBB* bb, cpSpatialIndexQueryFunc func, void* data) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpSpatialIndex.h:208:20
cpSpatialIndexQuery(index, obj, *bb, func, data);
}

__CLAW_API cpShapeFilter* __claw_cpShapeGetFilter(cpShapeFilter* __claw_result_, const cpShape* shape) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:157:25
(*__claw_result_) = cpShapeGetFilter(shape);
return __claw_result_;
}

__CLAW_API cpShape* __claw_cpCircleShapeNew(cpBody* body, cpFloat radius, cpVect* offset) {
// /home/borodust/devel/repo/bodge-projects/bodge-chipmunk/src/lib/chipmunk/include/chipmunk/cpShape.h:170:20
return cpCircleShapeNew(body, radius, *offset);
}

#if defined(__cplusplus)
}
#endif
